### ISSUE TITLE
ΓÖ╗∩╕Å Angular Playground #6 | Refactor data into Services

### ISSUE THREAD

**Issue by lukecookssw** [lukecookssw/someRepo#7]
[Relevant SugarLearning item](https://my.sugarlearning.com/SSW-FireBootCamp/items/14251/angular-creating-an-angular-playground-and-understanding-components)

### Description
We need to refactor our project data and dropdown data to come from a service, in preparation for the back-end team to give us access to their APIs.

### Tasks
- [ ] Get project data from `ProjectsService`
- [ ] Get dropdown data from `ProjectCategoryService`
- [ ] Ensure services are returning `Observables` in preparation for API integration

### Acceptance Criteria
- [ ] UI remains unchanged
- [ ] Functionality remains unchanged
